In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1


## Logistic Regression

In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

In [ ]:
X, y = load_iris(return_X_y=True)
lr_clf = LogisticRegression(random_state=0, max_iter=1000)

In [ ]:
lr_clf.fit(X, y)

LogisticRegression(max_iter=1000, random_state=0)

In [ ]:
print(lr_clf.predict(X[:2, :]))
print(lr_clf.predict_proba(X[:2, :]))
print(lr_clf.score(X, y))

[0 0]
[[9.81557202e-01 1.84427831e-02 1.44809203e-08]
 [9.71331260e-01 2.86687094e-02 3.01371913e-08]]
0.9733333333333334


In [ ]:
lr_clf.classes_

array([0, 1, 2])

In [ ]:
lr_clf.coef_

array([[-0.42415938,  0.96633485, -2.5160372 , -1.08205245],
       [ 0.53464109, -0.32039706, -0.20702001, -0.94324899],
       [-0.11048172, -0.64593779,  2.72305721,  2.02530144]])

In [ ]:
lr_clf.n_features_in_

4

## Linear Regression

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3

In [ ]:
reg = LinearRegression()
reg.fit(X, y)

LinearRegression()

In [ ]:
print(reg.coef_)
print(reg.intercept_)
print(reg.predict(np.array([[3, 5]])))

[1. 2.]
3.0000000000000018
[16.]


In [ ]:
y_pred = reg.predict(X)
print(mean_squared_error(y, y_pred))

1.9721522630525295e-31


### Q1. Write custom functions for accuracy and mean square error using numpy and compare yourresult with sklearn metric module functions

## Preprocessing

In [ ]:
data = np.array([[1],[2],[3],[4],[5]])
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
std_scaler = StandardScaler()

scaler.fit(data)
std_scaler.fit(data)

print(scaler.transform(data))
print(std_scaler.transform(data))

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


### Q2. Impliment a custom min-max scaler and standard scaler functions and compare the output with respective sklearn library functions

## Q3. Impliment a custom library with following modules and functionalities
```yaml
Custom Library Modules
├── preprocessing
│   ├── MinMaxScaler
│   ├── StandardScaler
├── metrics
│   ├── accuracy_score
│   ├── mean_squared_error
│   ├── mean_absolute_error
│   └── mean_absolute_percentage_error
├── model_selection
│   ├── train_test_split
```
