In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('spam.csv', encoding='Windows-1252')
data.head(9)

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN

In [3]:
# remove the unnamed columns

In [5]:
messages = data[['v1','v2']]
messages.columns = ["label", "text"]

In [7]:
# to vie w the complete data in columns
pd.set_option('display.max_colwidth', None)

messages.head(4)

label  \
0   ham   
1   ham   
2  spam   
3   ham   

                                                                                                                                                          text  
0                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
1                                                                                                                                Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  
3                                                                                                            U dun say so early hor... U c already then say...

In [8]:
# convert labels to 0 and 1, 1 for ham and 0 for spam
messages['label']=messages['label'].map({'ham':1,'spam':0})

<ipython-input-8-4b6a2a8a131a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  messages['label']=messages['label'].map({'ham':1,'spam':0})


In [10]:
messages.head()

label  \
0      1   
1      1   
2      0   
3      1   
4      1   

                                                                                                                                                          text  
0                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
1                                                                                                                                Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  
3                                                                                                            U dun say so early hor... U c already then say...  
4                                                                                                Nah I don't think he goes to usf, he lives around here though

In [12]:
messages.shape

(5572, 2)

In [11]:
from keras.preprocessing import text
tokenizer = text.Tokenizer()
# tokenizer from text librbary
# tokenizer converts words to integer values
# passint the text as inputs to tokenizer

tokenizer.fit_on_texts(list(messages['text']))

# passing these sms one by one

tokenized_texts = tokenizer.texts_to_sequences(messages['text'])
# converted to ingeer values

In [13]:
tokenized_texts[0]

[50,
 469,
 4410,
 841,
 751,
 657,
 64,
 8,
 1324,
 89,
 121,
 349,
 1325,
 147,
 2987,
 1326,
 67,
 58,
 4411,
 144]

In [16]:
len(messages['text'][0])

111

In [15]:
print(len(tokenized_texts[0]))
print(len(tokenized_texts[1]))

20
6


In [17]:
# to avoid the problem with different sizes
from keras.utils import pad_sequences
#going to pad the tokenizer text
X = pad_sequences(tokenized_texts, maxlen=100)
# it just add some zeros, and amke all sms to the length of 100

In [20]:
tokenized_texts[1]

[46, 336, 1495, 470, 6, 1929]

In [21]:
X[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,   46,  336, 1495,  470,    6,
       1929], dtype=int32)

In [22]:
#to get all the words
tokenizer.word_index

{'i': 1,
 'to': 2,
 'you': 3,
 'a': 4,
 'the': 5,
 'u': 6,
 'and': 7,
 'in': 8,
 'is': 9,
 'me': 10,
 'my': 11,
 'for': 12,
 'your': 13,
 'it': 14,
 'of': 15,
 'call': 16,
 'have': 17,
 'on': 18,
 '2': 19,
 'that': 20,
 'now': 21,
 'are': 22,
 'so': 23,
 'but': 24,
 'not': 25,
 'or': 26,
 'do': 27,
 'can': 28,
 'at': 29,
 "i'm": 30,
 'get': 31,
 'be': 32,
 'will': 33,
 'if': 34,
 'ur': 35,
 'with': 36,
 'just': 37,
 'no': 38,
 'we': 39,
 'this': 40,
 'gt': 41,
 '4': 42,
 'lt': 43,
 'up': 44,
 'when': 45,
 'ok': 46,
 'free': 47,
 'from': 48,
 'how': 49,
 'go': 50,
 'all': 51,
 'out': 52,
 'what': 53,
 'know': 54,
 'like': 55,
 'good': 56,
 'then': 57,
 'got': 58,
 'was': 59,
 'come': 60,
 'its': 61,
 'am': 62,
 'time': 63,
 'only': 64,
 'day': 65,
 'love': 66,
 'there': 67,
 'send': 68,
 'he': 69,
 'want': 70,
 'text': 71,
 'as': 72,
 'txt': 73,
 'one': 74,
 'going': 75,
 'by': 76,
 'home': 77,
 "i'll": 78,
 'need': 79,
 'about': 80,
 'r': 81,
 'lor': 82,
 'sorry': 83,
 'stop': 84,
 'st

In [23]:
len(tokenizer.word_index)

8920

In [26]:
#splitting the data to X and y
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, messages['label'].values, test_size = 0.2)

In [29]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding, SimpleRNN, Dropout

In [42]:
model = Sequential()
# embed the data, (convert them to a vector) before passing it

# https://keras.io/api/layers/core_layers/embedding/
# https://keras.io/api/layers/recurrent_layers/simple_rnn/


model.add(Embedding(input_dim = len(tokenizer.word_index)+1, output_dim = 128,input_length=100))
model.add(SimpleRNN(10))
model.add(Dropout(0.5))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

# try it with single dropout first, if overfitting comes up add one more drop out
# take output_dim = other values, 50 to 300 (often range)

In [43]:
model.compile(loss ='binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [44]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 100, 128)          1141888   
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 10)                1390      
                                                                 
 dropout_2 (Dropout)         (None, 10)                0         
                                                                 
 dense_2 (Dense)             (None, 50)                550       
                                                                 
 dropout_3 (Dropout)         (None, 50)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 1143879 (4.36 MB)
Trainable params: 1143

In [45]:
# 1141888/128 = 8921

In [46]:
model.fit(X_train,y_train,epochs = 10, validation_split = 0.1)

Epoch 1/10
126/126 [==============================] - 7s 40ms/step - loss: 0.4205 - accuracy: 0.8469 - val_loss: 0.2717 - val_accuracy: 0.8991
Epoch 2/10
126/126 [==============================] - 6s 49ms/step - loss: 0.1831 - accuracy: 0.9402 - val_loss: 0.1449 - val_accuracy: 0.9484
Epoch 3/10
126/126 [==============================] - 5s 39ms/step - loss: 0.0717 - accuracy: 0.9833 - val_loss: 0.1228 - val_accuracy: 0.9574
Epoch 4/10
126/126 [==============================] - 6s 49ms/step - loss: 0.0349 - accuracy: 0.9915 - val_loss: 0.1419 - val_accuracy: 0.9574
Epoch 5/10
126/126 [==============================] - 5s 40ms/step - loss: 0.0197 - accuracy: 0.9960 - val_loss: 0.1748 - val_accuracy: 0.9552
Epoch 6/10
126/126 [==============================] - 5s 44ms/step - loss: 0.0141 - accuracy: 0.9973 - val_loss: 0.1894 - val_accuracy: 0.9596
Epoch 7/10
126/126 [==============================] - 6s 44ms/step - loss: 0.0104 - accuracy: 0.9975 - val_loss: 0.1834 - val_accuracy: 0.9596

In [38]:
y_pred = model.predict(X_test)

35/35 [==============================] - 1s 11ms/step


In [39]:
y_pred[0]

array([0.9999999], dtype=float32)

In [40]:
#converting to 0 and 1

y_pred[y_pred>0.5] = 1
y_pred[y_pred<=0.5] = 0

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)


0.9865470852017937

In [47]:

model = Sequential()

model.add(Embedding(input_dim = len(tokenizer.word_index)+1, output_dim = 128,input_length=100))
model.add(LSTM(10))
model.add(Dropout(0.5))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

In [48]:
model.compile(loss ='binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [49]:
model.fit(X_train,y_train,epochs = 10, validation_split = 0.1)

Epoch 1/10
126/126 [==============================] - 17s 87ms/step - loss: 0.3394 - accuracy: 0.8881 - val_loss: 0.1281 - val_accuracy: 0.9596
Epoch 2/10
126/126 [==============================] - 8s 67ms/step - loss: 0.0771 - accuracy: 0.9870 - val_loss: 0.0565 - val_accuracy: 0.9821
Epoch 3/10
126/126 [==============================] - 7s 58ms/step - loss: 0.0263 - accuracy: 0.9970 - val_loss: 0.0555 - val_accuracy: 0.9843
Epoch 4/10
126/126 [==============================] - 8s 66ms/step - loss: 0.0116 - accuracy: 0.9983 - val_loss: 0.0770 - val_accuracy: 0.9776
Epoch 5/10
126/126 [==============================] - 8s 66ms/step - loss: 0.0062 - accuracy: 0.9993 - val_loss: 0.1009 - val_accuracy: 0.9821
Epoch 6/10
126/126 [==============================] - 7s 59ms/step - loss: 0.0036 - accuracy: 0.9995 - val_loss: 0.0870 - val_accuracy: 0.9843
Epoch 7/10
126/126 [==============================] - 8s 67ms/step - loss: 0.0027 - accuracy: 0.9995 - val_loss: 0.1215 - val_accuracy: 0.982

In [50]:
y_pred = model.predict(X_test)
y_pred[y_pred>0.5] = 1
y_pred[y_pred<=0.5] = 0

35/35 [==============================] - 2s 22ms/step


In [51]:
accuracy_score(y_pred,y_test)


0.9847533632286996

In [52]:
test1 = "Free entry in 2 a MNTHLY comp to win  tkts!!"
test1 = tokenizer.texts_to_sequences([test1])
test2 = pad_sequences(test1, maxlen=100)

In [53]:
output = model.predict(test2)

1/1 [==============================] - 0s 50ms/step


In [54]:
output

array([[0.0075289]], dtype=float32)

In [55]:
test1

[[47, 486, 8, 19, 4, 899, 2, 178, 1931]]

In [56]:
test2

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,   47,  486,    8,   19,    4,  899,    2,  178,
        1931]], dtype=int32)